name: Summarize Text and Generate HTML

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  summarize:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sumy

    - name: Run summarization script
      run: python summarize_text.py

    - name: Commit and push if changed
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add summaries.html
        git commit -m "Update summaries" || exit 0
        git push
